// <auto-generated/> >>> ignore StyleCop here
namespace Panelak.Database.OracleConsole
{
    using Panelak.Geometry;
    using Newtonsoft.Json;
    using System;

    /// <summary>
    /// JSON to SDO_GEOMETRY model converter for Newtonsoft.Json converter.
    /// </summary>
    public class SdoGeometryJsonConverter : JsonConverter
    {
        public override bool CanConvert(Type objectType) => objectType.Equals(typeof(Geometry));
        public override bool CanWrite => false;
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            SdoGeometry sdoGeometry = serializer.Deserialize<SdoGeometry>(reader);

            var converter = new SdoGeometryConverter();
            return converter.GeometryFromSdo(sdoGeometry);
        }
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer) => throw new NotImplementedException();
    }
}
