//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Panelak.Utils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Panelak.Utils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;outputFileName&quot;: &quot;wwwroot/js/site.js&quot;,
        ///    &quot;inputFiles&quot;: [
        ///      &quot;wwwroot/js_components/*.js&quot;,
        ///      &quot;Components/**/*.js&quot;,
        ///      &quot;Views/**/*.js&quot;
        ///    ],
        ///    &quot;minify&quot;: {
        ///      &quot;enabled&quot;: true,
        ///      &quot;renameLocals&quot;: false
        ///    },
        ///    &quot;sourceMap&quot;: false
        ///  }
        ///].
        /// </summary>
        public static string bundleconfig {
            get {
                return ResourceManager.GetString("bundleconfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;#@ template hostspecific=&quot;true&quot; debug=&quot;true&quot; language=&quot;C#&quot; compilerOptions=&quot;/langversion:7&quot; #&gt;
        ///&lt;#@ output extension=&quot;.cs&quot; #&gt;
        ///&lt;#@ import namespace=&quot;System.IO&quot; #&gt;
        ///&lt;#@ import namespace=&quot;System.Collections.Generic&quot; #&gt;
        ///// &lt;generated /&gt;
        ///namespace Intergraph.PVV.Web
        ///{
        ///	using Microsoft.AspNetCore.Mvc;
        ///	using Microsoft.AspNetCore.Mvc.Razor;
        ///	using System.Collections.Generic;
        ///	
        ///	/// &lt;summary&gt;
        ///	/// Allows loading of views by the filename only. This asssumes that all view names are unique.
        ///	/// &lt;/summary&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FlatViewListViewLocationExpander {
            get {
                return ResourceManager.GetString("FlatViewListViewLocationExpander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!doctype html&gt;
        ///&lt;html class=&quot;no-js&quot; lang=&quot;&quot;&gt;
        ///&lt;head&gt;
        ///  &lt;meta charset=&quot;utf-8&quot;&gt;
        ///  &lt;title&gt;Panelak.Utils tool page&lt;/title&gt;
        ///  &lt;meta name=&quot;description&quot; content=&quot;&quot;&gt;
        ///  &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1&quot;&gt;
        ///  &lt;link href=&quot;https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css&quot; rel=&quot;stylesheet&quot; integrity=&quot;sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh&quot; crossorigin=&quot;anonymous&quot;&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;main role=&quot;main&quot; class=&quot;container&quot;&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Index {
            get {
                return ResourceManager.GetString("Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string nlog {
            get {
                return ResourceManager.GetString("nlog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to namespace Project
        ///{
        ///    using Microsoft.AspNetCore.Builder;
        ///    using Microsoft.AspNetCore.Hosting;
        ///    using Microsoft.Extensions.Hosting;
        ///    using Microsoft.Extensions.Logging;
        ///    using NLog.Web;
        ///    using System;
        ///
        ///    public class Program
        ///    {
        ///        public static void Main(string[] args)
        ///        {
        ///            // NLog: setup the logger first to catch all errors
        ///            var logger = NLogBuilder.ConfigureNLog(&quot;nlog.config&quot;).GetCurrentClassLogger();
        ///            try
        ///            {
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Program_3_1 {
            get {
                return ResourceManager.GetString("Program_3_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;index.html&quot;: {
        ///    &quot;ResourceName&quot;: &quot;Index&quot;,
        ///    &quot;ContentType&quot;: &quot;text/html&quot;,
        ///    &quot;Description&quot;: &quot;This page&quot;
        ///  },
        ///  &quot;FlatViewListViewLocationExpander.tt&quot;: {
        ///    &quot;ResourceName&quot;: &quot;FlatViewListViewLocationExpander&quot;,
        ///    &quot;ContentType&quot;: &quot;text/plain&quot;,
        ///    &quot;Description&quot;: &quot;T4 template source code for generating a flat list of all of your views in your project in a generated view location expander&quot;
        ///  },
        ///  &quot;nlog.config&quot;: {
        ///    &quot;ResourceName&quot;: &quot;nlog&quot;,
        ///    &quot;ContentType&quot;: &quot;application/xml&quot;,
        ///    &quot;Descrip [rest of string was truncated]&quot;;.
        /// </summary>
        public static string staticfiles_metadata {
            get {
                return ResourceManager.GetString("staticfiles_metadata", resourceCulture);
            }
        }
    }
}
